version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: ai_web_extension
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: